CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `CUSTOMER_FNAME` varchar(255) NOT NULL,
  `CUSTOMER_LNAME` varchar(255) NOT NULL,
  `CUSTOMER_EMAIL` varchar(255) NOT NULL,
  `CUSTOMER_PHONE` bigint NOT NULL,
  `CUSTOMER_STREET` varchar(255) NOT NULL,
  `CUSTOMER_CITY` varchar(50) NOT NULL,
  `CUSTOMER_STATE` varchar(2) NOT NULL,
  `CUSTOMER_ZIP` int NOT NULL,
  `CUSTOMER_RATING` int NOT NULL,
  `WELL_DEPTH` int NOT NULL,
  `WELL_LOCATION` varchar(50) NOT NULL,
  `WELL_FLOWRATE` int NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE KEY `CUSTOMER_ID_UNIQUE` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CC_INFO` (
  `CC_NUMBER` int NOT NULL,
  `CC_EXPIRATION` varchar(5) NOT NULL,
  `CC_CVC` int NOT NULL,
  `CC_STREET` varchar(255) NOT NULL,
  `CC_CITY` varchar(50) NOT NULL,
  `CC_STATE` varchar(2) NOT NULL,
  `CC_ZIP` int NOT NULL,
  `CUSTOMER_ID` int(5) unsigned zerofill NOT NULL,
  PRIMARY KEY (`CC_NUMBER`),
  UNIQUE KEY `CC_NUMBER_UNIQUE` (`CC_NUMBER`),
  KEY `CUSTOMER_ID_idx` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_FNAME` varchar(255) NOT NULL,
  `EMPLOYEE_LNAME` varchar(255) NOT NULL,
  `EMPLOYEE_EMAIL` varchar(255) NOT NULL,
  `EMPLOYEE_PHONE` bigint NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `EMPLOYEE_ID_UNIQUE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `EMPLOYEE_INFO` (
  `EMPLOYEE_SSN` int NOT NULL,
  `EMPLOYEE_ID` int(5) unsigned zerofill NOT NULL,
  `EMPLOYEE_USERNAME` varchar(50) NOT NULL,
  `EMPLOYEE_PASSWORD` varchar(255) NOT NULL,
  `EMPLOYEE_DLN` bigint NOT NULL,
  `EMPLOYEE_STREET` varchar(255) NOT NULL,
  `EMPLOYEE_CITY` varchar(50) NOT NULL,
  `EMPLOYEE_STATE` varchar(2) NOT NULL,
  `EMPLOYEE_ZIP` int NOT NULL,
  `EMPLOYEE_ADMIN` tinyint NOT NULL,
  PRIMARY KEY (`EMPLOYEE_SSN`),
  UNIQUE KEY `EMPLOYEE_SSN_UNIQUE` (`EMPLOYEE_SSN`),
  UNIQUE KEY `EMPLOYEE_USERNAME_UNIQUE` (`EMPLOYEE_USERNAME`),
  UNIQUE KEY `EMPLOYEE_ID_UNIQUE` (`EMPLOYEE_ID`),
  CONSTRAINT `EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `JOB` (
  `JOB_ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `JOB_CUSTOMER` int(5) unsigned zerofill NOT NULL,
  `JOB_EMPLOYEE` int(5) unsigned zerofill NOT NULL,
  `JOB_START` date NOT NULL,
  `JOB_END` date NOT NULL,
  `JOB_COST` decimal(7,2) NOT NULL,
  `JOB_DESCRIPTION` varchar(255) NOT NULL,
  PRIMARY KEY (`JOB_ID`),
  UNIQUE KEY `JOB_ID_UNIQUE` (`JOB_ID`),
  KEY `CUSTOMER_ID_index` (`JOB_CUSTOMER`),
  KEY `EMPLOYEE_ID_index` (`JOB_EMPLOYEE`),
  CONSTRAINT `JOB_CUSTOMER` FOREIGN KEY (`JOB_CUSTOMER`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`),
  CONSTRAINT `JOB_EMPLOYEE` FOREIGN KEY (`JOB_EMPLOYEE`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` varchar(50) NOT NULL,
  `PRODUCT_PRICE` decimal(7,2) NOT NULL,
  `PRODUCT_DESCRIPTION` varchar(255) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE KEY `PRODUCT_ID_UNIQUE` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERVICES` (
  `SERVICE_ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `SERVICE_PRICE` decimal(7,2) NOT NULL,
  `SERVICE_DESCRIPTION` varchar(255) NOT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  UNIQUE KEY `SERVICE_ID_UNIQUE` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
