CREATE TABLE "CUSTOMER" (
	"CUSTOMER_ID"	INTEGER NOT NULL UNIQUE,
	"CUSTOMER_LNAME"	TEXT NOT NULL,
	"CUSTOMER_FNAME"	TEXT NOT NULL,
	"CUSTOMER_PHONE"	TEXT NOT NULL UNIQUE,
	"CUSTOMER_ADDRESS"	TEXT NOT NULL UNIQUE,
	"CUSTOMER_RATING"	INTEGER NOT NULL DEFAULT 0,
	"WELL_DEPTH"	INTEGER NOT NULL DEFAULT 0,
	"WELL_LOCATION"	TEXT NOT NULL,
	"WELL_FLOWRATE"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("CUSTOMER_ID" AUTOINCREMENT)
);

CREATE TABLE "CC_INFO" (
	"CC_NUMBER"	INTEGER NOT NULL UNIQUE,
	"CUSTOMER_ID"	INTEGER NOT NULL,
	"CC_EXPIRATION"	TEXT NOT NULL,
	"CC_CVC"	INTEGER NOT NULL,
	"CC_ZIPCODE"	INTEGER NOT NULL,
	FOREIGN KEY("CUSTOMER_ID") REFERENCES "CUSTOMER",
	PRIMARY KEY("CC_NUMBER")
);

CREATE TABLE "EMPLOYEE" (
	"EMPLOYEE_ID"	INTEGER NOT NULL UNIQUE,
	"EMPLOYEE_LNAME"	TEXT NOT NULL,
	"EMPLOYEE_FNAME"	TEXT NOT NULL,
	"EMPLOYEE_PHONE"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("EMPLOYEE_ID" AUTOINCREMENT)
);

CREATE TABLE "EMPLOYEE_INFO" (
	"EMPLOYEE_SSN"	TEXT NOT NULL UNIQUE,
	"EMPLOYEE_ID"	INTEGER NOT NULL UNIQUE,
	"EMPLOYEE_DLN"	TEXT NOT NULL UNIQUE,
	"EMPLOYEE_ADDRESS"	TEXT NOT NULL UNIQUE,
	"EMPLOYEE_PERMISSIONS"	TEXT NOT NULL,
	FOREIGN KEY("EMPLOYEE_ID") REFERENCES "EMPLOYEE",
	PRIMARY KEY("EMPLOYEE_SSN")
);

CREATE TABLE "JOB" (
	"JOB_ID"	INTEGER NOT NULL UNIQUE,
	"CUSTOMER_ID"	TEXT NOT NULL,
	"EMPLOYEE_ID"	INTEGER NOT NULL,
	"JOB_START"	TEXT NOT NULL,
	"JOB_END"	TEXT NOT NULL,
	"JOB_COST"	TEXT NOT NULL,
	"JOB_INVOICE"	BLOB NOT NULL UNIQUE,
	FOREIGN KEY("EMPLOYEE_ID") REFERENCES "EMPLOYEE"("EMPLOYEE_ID"),
	FOREIGN KEY("CUSTOMER_ID") REFERENCES "CUSTOMER"("CUSTOMER_ID"),
	PRIMARY KEY("JOB_ID" AUTOINCREMENT)
);