CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `CUSTOMER_FNAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_LNAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_EMAIL` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_PHONE` bigint(20) NOT NULL,
  `CUSTOMER_STREET` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_CITY` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_STATE` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CUSTOMER_ZIP` int(11) NOT NULL,
  `CUSTOMER_RATING` int(11) NOT NULL,
  `WELL_DEPTH` int(11) NOT NULL,
  `WELL_LOCATION` text COLLATE utf8_unicode_ci NOT NULL,
  `WELL_FLOWRATE` varchar(55) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE KEY `CUSTOMER_ID_UNIQUE` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `CC_INFO` (
  `CC_NUMBER` bigint(16) unsigned zerofill NOT NULL DEFAULT '0000000000000000',
  `CC_EXPIRATION` int(4) unsigned zerofill NOT NULL DEFAULT '0000',
  `CC_CVC` int(3) unsigned zerofill NOT NULL DEFAULT '000',
  `CC_ZIP` int(5) unsigned zerofill NOT NULL DEFAULT '00000',
  `CUSTOMER_ID` int(5) unsigned zerofill NOT NULL,
  `CC_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CC_ID`),
  UNIQUE KEY `CC_ID_UNIQUE` (`CC_ID`),
  KEY `CUSTOMER_ID_idx` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `EMPLOYEE` (
  `EMPLOYEE_ID` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_FNAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_LNAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_EMAIL` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_PHONE` bigint(20) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `EMPLOYEE_ID_UNIQUE` (`EMPLOYEE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `EMPLOYEE_INFO` (
  `EMPLOYEE_SSN` int(11) NOT NULL,
  `EMPLOYEE_ID` int(5) unsigned zerofill NOT NULL,
  `EMPLOYEE_USERNAME` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_PASSWORD` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_DLN` bigint(20) NOT NULL,
  `EMPLOYEE_STREET` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_CITY` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_STATE` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLOYEE_ZIP` int(11) NOT NULL,
  `EMPLOYEE_ADMIN` tinyint(4) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_SSN`),
  UNIQUE KEY `EMPLOYEE_SSN_UNIQUE` (`EMPLOYEE_SSN`),
  UNIQUE KEY `EMPLOYEE_USERNAME_UNIQUE` (`EMPLOYEE_USERNAME`),
  UNIQUE KEY `EMPLOYEE_ID_UNIQUE` (`EMPLOYEE_ID`),
  KEY `EMPLOYEE_ADMIN` (`EMPLOYEE_ADMIN`) USING BTREE COMMENT 'Used to authenticate user permissions.',
  CONSTRAINT `EMPLOYEE_ID` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


INSERT INTO `avidnexu_long_term_well_solutions`.`EMPLOYEE`
--Employee General Information entered in these fields
(`0001`,
`EMPLOYEE_FNAME`,
`EMPLOYEE_LNAME`,
`EMPLOYEE_EMAIL`,
`EMPLOYEE_PHONE`)
VALUES
--Do not change these values
(<{EMPLOYEE_ID: }>,
<{EMPLOYEE_FNAME: }>,
<{EMPLOYEE_LNAME: }>,
<{EMPLOYEE_EMAIL: }>,
<{EMPLOYEE_PHONE: }>);


INSERT INTO `avidnexu_long_term_well_solutions`.`EMPLOYEE_INFO`
--Employee Sensitive Information entered in these fields
--EMPLOYEE_USERNAME and EMPLOYEE_PASSWORD will be used to access the system on first use
--EMPLOYEE_ADMIN field must be set to 'Yes' in order to access the system on first use
(`EMPLOYEE_SSN`,
`EMPLOYEE_ID`,
`EMPLOYEE_USERNAME`,
`EMPLOYEE_PASSWORD`,
`EMPLOYEE_DLN`,
`EMPLOYEE_STREET`,
`EMPLOYEE_CITY`,
`EMPLOYEE_STATE`,
`EMPLOYEE_ZIP`,
`EMPLOYEE_ADMIN`)
VALUES
--Do not change these values
(<{EMPLOYEE_SSN: }>,
<{EMPLOYEE_ID: }>,
<{EMPLOYEE_USERNAME: }>,
<{EMPLOYEE_PASSWORD: }>,
<{EMPLOYEE_DLN: }>,
<{EMPLOYEE_STREET: }>,
<{EMPLOYEE_CITY: }>,
<{EMPLOYEE_STATE: }>,
<{EMPLOYEE_ZIP: }>,
<{EMPLOYEE_ADMIN: }>);


CREATE TABLE `JOB` (
  `JOB_ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `JOB_CUSTOMER` int(5) unsigned zerofill NOT NULL,
  `JOB_START` date NOT NULL,
  `JOB_END` date NOT NULL,
  `JOB_DESCRIPTION` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `JOB_PAID` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`JOB_ID`),
  UNIQUE KEY `JOB_ID_UNIQUE` (`JOB_ID`),
  KEY `CUSTOMER_ID_index` (`JOB_CUSTOMER`),
  CONSTRAINT `JOB_CUSTOMER` FOREIGN KEY (`JOB_CUSTOMER`) REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `MATERIAL` (
  `MATERIAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MATERIAL_PRICE` decimal(7,2) NOT NULL,
  `MATERIAL_DESCRIPTION` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `JOB_ID` int(10) unsigned zerofill NOT NULL,
  PRIMARY KEY (`MATERIAL_ID`),
  UNIQUE KEY `MATERIAL_ID_UNIQUE` (`MATERIAL_ID`),
  KEY `MATERIAL_JOB_ind` (`JOB_ID`),
  KEY `MATERIAL_PRICE` (`MATERIAL_PRICE`),
  CONSTRAINT `JOB_ID` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`JOB_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `LABOR` (
  `LABOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LABOR_PRICE` decimal(7,2) NOT NULL,
  `LABOR_DESCRIPTION` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `JOB_ID` int(10) unsigned zerofill NOT NULL,
  PRIMARY KEY (`LABOR_ID`),
  UNIQUE KEY `LABOR_ID_UNIQUE` (`LABOR_ID`),
  KEY `JOB_ID` (`JOB_ID`),
  KEY `LABOR_PRICE` (`LABOR_PRICE`),
  CONSTRAINT `LABOR_ibfk_1` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`JOB_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `FEE` (
  `FEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FEE_PRICE` decimal(7,2) NOT NULL,
  `FEE_DESCRIPTION` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `JOB_ID` int(10) unsigned zerofill NOT NULL,
  PRIMARY KEY (`FEE_ID`),
  UNIQUE KEY `FEE_ID_UNIQUE` (`FEE_ID`),
  KEY `JOB_ID` (`JOB_ID`),
  CONSTRAINT `FEE_ibfk_1` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`JOB_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `JOB_EMPLOYEE` (
  `JOB_EMPLOYEE_ID` int(5) unsigned zerofill NOT NULL,
  `JOB_ID` int(10) unsigned zerofill NOT NULL,
  `ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `JOB_EMPLOYEE_ibfk_1` (`JOB_ID`),
  CONSTRAINT `JOB_EMPLOYEE_ibfk_1` FOREIGN KEY (`JOB_ID`) REFERENCES `JOB` (`JOB_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

